-- 🚨 VETERAN GUTTERS DATABASE SETUP (FULL) 🚨
-- Run this ENTIRE script in the Supabase SQL Editor.

-- 1. Create the 'leads' table
CREATE TABLE IF NOT EXISTS leads (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    name text not null,
    phone text not null,
    service text,
    notes text,
    status text default 'new'
);

-- 2. Create the 'projects' table (for the Gallery)
CREATE TABLE IF NOT EXISTS projects (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    title text,
    image_url text not null,
    description text
);

-- 3. Enable Security (Locks the tables)
ALTER TABLE leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;

-- 4. Allow Public Inserts (Unlocks the contact form)
DROP POLICY IF EXISTS "Public Insert" ON leads;
CREATE POLICY "Public Insert" 
ON leads FOR INSERT 
TO anon 
WITH CHECK (true);

-- 5. Allow Admin View (For you to see data)
DROP POLICY IF EXISTS "Admin View" ON leads;
CREATE POLICY "Admin View"
ON leads FOR SELECT
TO authenticated
USING (true);

-- 6. Allow Public Read on Projects (So Gallery works)
DROP POLICY IF EXISTS "Public Read Projects" ON projects;
CREATE POLICY "Public Read Projects"
ON projects FOR SELECT
TO anon
USING (true);
